include:
  - project: 'gnome/citemplates'
    file: 'flatpak/flatpak_ci_initiative.yml'
  - component: gitlab.gnome.org/GNOME/citemplates/release-service@master
    inputs:
      dist-job-name: "flatpak devel"
      tarball-artifact-path: "${TARBALL_ARTIFACT_PATH}"

variables:
    GIT_SUBMODULE_STRATEGY: normal
    BUNDLE: "gnome-logs.flatpak"
    FLATPAK_MODULE: "gnome-logs"
    TARBALL_ARTIFACT_PATH: ".flatpak-builder/build/${FLATPAK_MODULE}/_flatpak_build/meson-dist/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.xz"

stages:
    - test
    - deploy

flatpak devel:
    stage: test
    variables:
        MANIFEST_PATH: "org.gnome.Logs.json"
        MESON_ARGS: "-Dtests=true"
        RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
        APP_ID: "org.gnome.Logs"
    extends: .flatpak

nightly:
    extends: '.publish_nightly'
    dependencies: ['flatpak devel']
    needs: ['flatpak devel']
