include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

variables:
    GIT_SUBMODULE_STRATEGY: normal
    BUNDLE: "gnome-logs.flatpak"

stages:
    - test
    - deploy

flatpak devel:
    stage: test
    variables:
        MANIFEST_PATH: "org.gnome.Logs.json"
        MESON_ARGS: "-Dtests=true"
        FLATPAK_MODULE: "gnome-logs"
        RUNTIME_REPO: "https://sdk.gnome.org/gnome.flatpakrepo"
        APP_ID: "org.gnome.Logs"
    extends: .flatpak

nightly:
    extends: '.publish_nightly'
    dependencies: ['flatpak devel']
    needs: ['flatpak devel']
